spring.application.name=Service-discovery
server.port=8761
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.show-details=when-authorized
management.metrics.distribution.percentiles-histogram.http.server.requests=true
