spring.application.name=AI-SERVICE
server.port=8083
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

rabbitmq.queues.content-submission=content-submission-queue

logging.level.org.springframework.amqp=DEBUG
logging.level.org.springframework.amqp.rabbit=DEBUG
ai.python-service.url=http://127.0.0.1:5000/toxicity-test
rabbitmq.queues.moderation-queue=moderation-queue
rabbitmq.exchanges.moderation-exchange=moderation-queue-exchange
rabbitmq.routing-keys.moderation-key=moderation-queue-key

management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.show-details=when-authorized
management.metrics.distribution.percentiles-histogram.http.server.requests=true
